import img from "@/assets/driver_image-two.png";

export const userTableHeaders = [
  { label: "Image", key: "image" },
  { label: "Name", key: "name" },
  { label: "email", key: "email" },
  { label: "Address", key: "address" },
  { label: "Date", key: "paymentMethod" },
  { label: "Status", key: "status" },
  { label: "Action", key: "date" },
];

export const userData = [
  {
    id: "1",
    avatar: img,
    name: "Albert Flores",
    phone: "077 5665 8785",
    location: "55455, Saudi Arabia",
    totalBooking: "02",
    date: "March 6, 2025",
    status: "Blocked",
  },
  {
    id: "2",
    avatar: img,
    name: "Cameron Williamson",
    phone: "070 3397 6621",
    location: "55455, Saudi Arabia",
    totalBooking: "06",
    date: "March 23, 2015",
    status: "Active",
  },
  {
    id: "3",
    avatar: img,
    name: "Albert Flores",
    phone: "077 5665 8785",
    location: "55455, Saudi Arabia",
    totalBooking: "02",
    date: "March 6, 2025",
    status: "Blocked",
  },
  {
    id: "4",
    avatar: img,
    name: "Cameron Williamson",
    phone: "070 3397 6621",
    location: "55455, Saudi Arabia",
    totalBooking: "06",
    date: "March 23, 2015",
    status: "Active",
  },
  {
    id: "5",
    avatar: img,
    name: "Albert Flores",
    phone: "077 5665 8785",
    location: "55455, Saudi Arabia",
    totalBooking: "02",
    date: "March 6, 2025",
    status: "Blocked",
  },
  {
    id: "6",
    avatar: img,
    name: "Cameron Williamson",
    phone: "070 3397 6621",
    location: "55455, Saudi Arabia",
    totalBooking: "06",
    date: "March 23, 2015",
    status: "Active",
  },
  // Add more mock data as needed
]
